### ISSUE TITLE
`npm install` fails for 3.7.4 due to missing pnpm executable

### ISSUE THREAD

**Issue by fspoettel** [sampotts/plyr#2639]
This affects anyone that does not have `pnpm` installed.
```
npm ERR! code 126
npm ERR! path <snip>/node_modules/plyr
npm ERR! command failed
npm ERR! command sh -c pnpm build
npm ERR! Volta error: Could not find executable "pnpm"
npm ERR! 
npm ERR! Use `volta install` to add a package to your toolchain (see `volta help install` for more info).
npm ERR! Error details written to <snip>/.volta/log/volta-error-2023-03-09_16_16_50.648.log

npm ERR! A complete log of this run can be found in:
npm ERR!    <snip>/.npm/_logs/2023-03-09T15_16_50_317Z-debug-0.log
```

### Expected behaviour

Installation should work and not rely on tools that might not be installed.

### Actual behaviour

Installation fails.

### Steps to reproduce

Run `npm install plyr` without having `pnpm` in $PATH.

### Environment

- Browser: -
- Version: -
- Operating System: Pop!_OS 
- Version: 22.04

**Comment by Zsavajji** [comment]
I think that the postinstall script command is plain wrong, it should not rebuild itself :/

**Comment by tglazier754** [comment]
Issue when trying to yarn add plyr-react.

`[4/4] Building fresh packages...
[2/2] ⢀ plyr
error C:\Users\taylo\Documents\Oracle\oracle-frontend\node_modules\plyr: Command failed.
Exit code: 1
Command: pnpm build
Arguments:
Directory: C:\Users\taylo\Documents\Oracle\oracle-frontend\node_modules\plyr
Output:
> plyr@3.7.4 build C:\Users\taylo\Documents\Oracle\oracle-frontend\node_modules\plyr
> gulp build`

**Comment by hykilpikonna** [comment]
Can replicate

![image](https://user-images.githubusercontent.com/22280294/224136785-71368428-6302-45f4-80ab-22df2cfd6113.png)

**Comment by Edropem** [comment]
same here on `npm install`
`[Exec Stream Pumper] [INFO] npm ERR! Failed at the plyr@3.7.4 postinstall script.`

**Comment by sampotts** [comment]
Apologies for this. I've pushed 3.7.5, which replaces references to `pnpm` with `npm` in scripts, which should resolve this issue. Report back if not.

**Comment by tglazier754** [comment]
@sampotts I'm still running into issues when trying to yarn add either plyr directly or plyr-react. It doesn't like build regardless of which package manager does it - does it need an npm install as well?

**Comment by sampotts** [comment]
You'd need to install dependencies before building yep. That's not changed. What error are you seeing?

**Comment by tglazier754** [comment]
> You'd need to install dependencies before building yep. That's not changed. What error are you seeing?

I hope that I'm just simply missing something simple. I'm using @fspoettel 's suggestion right now to override to 3.7.3

If I install plyr-react, plyr as a dependency gives me this : 
```
error C:\Users\taylo\Documents\Oracle\oracle-frontend\node_modules\plyr: Command failed.
Exit code: 1
Command: npm run build
Arguments:
Directory: C:\Users\taylo\Documents\Oracle\oracle-frontend\node_modules\plyr
Output:
> plyr@3.7.5 build
> gulp build
```

If I install plyr directly, I get a lot of "gulp module not found" issues. I essentially can resolve them by adding them all individually to my main project, which isn't right : 
```
Exit code: 1
Command: npm run build
Arguments:
Directory: C:\Users\taylo\Documents\Oracle\oracle-frontend\node_modules\plyr
Output:
> plyr@3.7.5 build
> gulp build

Error: Cannot find module 'gulp-hub'
Require stack:
- C:\Users\taylo\Documents\Oracle\oracle-frontend\node_modules\plyr\gulpfile.js
- C:\Users\taylo\Documents\Oracle\oracle-frontend\node_modules\gulp-cli\lib\shared\require-or-import.js
- C:\Users\taylo\Documents\Oracle\oracle-frontend\node_modules\gulp-cli\lib\versioned\^4.0.0\index.js
- C:\Users\taylo\Documents\Oracle\oracle-frontend\node_modules\gulp-cli\index.js
- C:\Users\taylo\Documents\Oracle\oracle-frontend\node_modules\gulp\bin\gulp.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1051:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\taylo\Documents\Oracle\oracle-frontend\node_modules\plyr\gulpfile.js:6:21)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1051:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\taylo\\Documents\\Oracle\\oracle-frontend\\node_modules\\plyr\\gulpfile.js',
    'C:\\Users\\taylo\\Documents\\Oracle\\oracle-frontend\\node_modules\\gulp-cli\\lib\\shared\\require-or-import.js',
    'C:\\Users\\taylo\\Documents\\Oracle\\oracle-frontend\\node_modules\\gulp-cli\\lib\\versioned\\^4.0.0\\index.js',
    'C:\\Users\\taylo\\Documents\\Oracle\\oracle-frontend\\node_modules\\gulp-cli\\index.js',
```

**Comment by nicomelamed** [comment]
Hi @sampotts the issue still there:
[Exec Stream Pumper] [INFO] npm ERR! plyr@3.7.5 postinstall: `npm run build`

**Comment by sampotts** [comment]
Ah, damn. I've completely removed the `postinstall` script in `3.7.6` (just published). Give that a go.

**Comment by sampotts** [comment]
Sorry about all this folks. I didn't realise it would cause such problems. Please report back with any issues and I'll continue working on resolving them.

**Comment by sampotts** [comment]
Great news. Thanks for getting back to me and sorry about adding to the workload!
